name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"A push has been made to the main branch by ${AUTHOR_NAME}. Commit message: ${COMMIT_MESSAGE}\"}" \
               $DISCORD_WEBHOOK_URL
