name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          AUTHOR_EMAIL=$(git log -1 --pretty=format:'%ae')
          COMMIT_HASH=$(git log -1 --pretty=format:'%h')
          COMMIT_DATE=$(git log -1 --pretty=format:'%cd' --date=short)
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')
          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
          REPO_NAME=$(basename $(git rev-parse --show-toplevel))
          COMMIT_URL="https://github.com/RahulChhatbar/Text-Generation/commit/${COMMIT_HASH}"

          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"A push has been made to the branch *${BRANCH_NAME}* in repository *${REPO_NAME}*!\\nAuthor: ${AUTHOR_NAME} <${AUTHOR_EMAIL}>\\nCommit Hash: ${COMMIT_HASH}\\nCommit Date: ${COMMIT_DATE}\\nCommit Message: ${COMMIT_MESSAGE}\\nCommit URL: ${COMMIT_URL}\"}" \
               $DISCORD_WEBHOOK_URL

