name: Sync To HuggingFace

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Sync to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push https://RahulChhatbar:$HF_TOKEN@huggingface.co/spaces/RahulChhatbar/completion main
